### PR TITLE
 bugfix for processPushNotification function

### PR DESCRIPTION
**Pull request by josh88versa**
Dart `Map` data structure doesn't match Java `JSONObject` type. Therefore it is best to serialise the data when passing data from flutter project to plugin.

### CODE REVIEW

**Comment by darshanclevertap** [comment]
@josh88versa Thanks for raising this PR, our primary Flutter dev is out on PTO this week. I will try to get this PR merged and released in the next version as soon as possible. Will provide an update soon. Thank you for your patience.

**Comment by josh88versa** [comment]
No worries. Thanks @darshanclevertap.

**Comment by darshanclevertap** [comment]
@shivamsharma2710 can you check this?

**Comment by shivamsharma2710** [comment]
> @shivamsharma2710 can you check this?
Yes, I will review this.

**Comment by shivamsharma2710** [comment]
Hi @josh88versa,

Since your solution does not align with our usual practice, we have addressed this issue in a new PR -> https://github.com/CleverTap/clevertap-flutter/pull/179

This will be included in the upcoming release of our CleverTap Flutter SDK v1.7.0.

**Pull request closed without merging**
